'use strict'

const Route = use('Route')
Route.on('/test').render('test')
Route.get('/', 'PropertyController.index')
Route.get('/advertisments/create', 'PropertyController.create').middleware('auth')
Route.post('/advertisments/create', 'PropertyController.doCreate').middleware('auth')
Route.get('/advertisments/:id', 'PropertyController.show')
Route.get('/advertisments/create/:id/upload', 'FileController.show').middleware('auth')
Route.post('/advertisments/create/upload', 'FileController.store').middleware('auth')
Route.get('/advertisments/create/upload/file/:id/delete', 'FileController.delete').middleware('auth')
Route.delete('/advertisments/create/upload/file/:id', 'FileController.delete').middleware('auth')
Route.get('/advertisments/:id/edit', 'PropertyController.edit').middleware('auth')
Route.post('/advertisments/:id/edit', 'PropertyController.doEdit').middleware('auth')
Route.get('/advertisments/:id/delete', 'PropertyController.doDelete').middleware('auth')
Route.get('/advertisments/:id/favorite', 'PropertyController.addFavorite').middleware('auth')
Route.get('/myfavorites', 'PropertyController.myFavorites').middleware('auth')
Route.delete('/advertisments/:id', 'PropertyController.doDelete')
Route.get('/advertisments', 'PropertyController.search')
Route.get('/register', 'UserController.register')
Route.post('/register', 'UserController.doRegister')
Route.get('/login', 'UserController.login')
Route.post('/login', 'UserController.doLogin')
Route.get('/logout', 'UserController.doLogout')

Route.post('/test', 'FileController.store')
Route.group('ajax', function () {
  Route.delete('/advertisments/:id/delete', 'PropertyController.ajaxDelete').middleware('auth')  
  Route.post('/login', 'UserController.ajaxLogin')
  Route.post('/advertisments/create/upload', 'FileController.ajaxStore')
}).prefix('/ajax')